"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Check, CircleAlert, Pause, Play, RotateCcw, UserRoundCog, Eye } from "lucide-react";
import { api, ApiError } from "../../../../lib";

type UsageMetrics = { calls?: number; prompt_tokens?: number; completion_tokens?: number; total_tokens?: number; latency_ms?: number; estimated_cost?: number | null; cost_status?: string; provider?: string; model?: string };
type Step = { id: string; stage: string; status: string; attempt: number; output_artifact_id?: string; output_payload?: Record<string, any>; error_code?: string; error_summary?: string; token_usage?: Record<string, any>; usage_metrics?: UsageMetrics };
type Run = { id: string; status: string; current_stage: string; pause_reason?: string; next_action?: string; current_chapter_id?: string; updated_at?: string; settings?: Record<string, any>; token_usage?: Record<string, any>; usage_metrics?: UsageMetrics; context?: Record<string, any>; steps: Step[] };

const stages = ["IDEA", "FRAMING", "CAST_PREPARATION", "WORLD_BUILDING", "STORY_MACRO", "VOLUME_PLANNING", "CHAPTER_PLANNING", "CHAPTER_DETAIL", "CHAPTER_EXECUTION", "QUALITY_REVIEW", "QUALITY_REPAIR", "AUTHOR_ADOPTION", "NEXT_CHAPTER", "COMPLETED"];
const labels: Record<string, string> = { IDEA: "灵感", FRAMING: "方向评分", CAST_PREPARATION: "角色准备", WORLD_BUILDING: "世界边界", STORY_MACRO: "故事主线", VOLUME_PLANNING: "卷纲", CHAPTER_PLANNING: "章节任务", CHAPTER_DETAIL: "章节详情", CHAPTER_EXECUTION: "章节正文", QUALITY_REVIEW: "质量审核", QUALITY_REPAIR: "自动修复", AUTHOR_ADOPTION: "自动采用", NEXT_CHAPTER: "下一章", COMPLETED: "整本完成", PAUSED: "已暂停", FAILED: "失败", BLOCKED: "已阻塞" };

export default function AutoDirectorPage({ params }: { params: { id: string } }) {
  const [run, setRun] = useState<Run>(); const [draft, setDraft] = useState<Record<string, any>>(); const [quality, setQuality] = useState<Record<string, any>>(); const [task, setTask] = useState<Record<string, any>>(); const [chapters, setChapters] = useState<Array<Record<string, any>>>([]); const [directionOpen, setDirectionOpen] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void api(`/projects/${params.id}/auto-director/runs`).then((items: unknown) => { const runs = items as Run[]; const active = runs.filter((item) => ["RUNNING", "PAUSED", "BLOCKED"].includes(item.status)); const current = [...active, ...runs.filter((item) => !active.includes(item))].sort((a, b) => String(b.updated_at || b.id).localeCompare(String(a.updated_at || a.id)))[0]; if (current) setRun(current); }).catch(() => undefined); void api(`/projects/${params.id}/chapters`).then((items: unknown) => setChapters((items as Array<Record<string, any>>).filter((item) => item.active !== false).sort((a, b) => Number(a.number || 0) - Number(b.number || 0)))).catch(() => undefined); }, [params.id]);
  useEffect(() => { if (!run || ["COMPLETED", "FAILED", "BLOCKED"].includes(run.status)) return; const timer = window.setInterval(() => { void api(`/projects/${params.id}/auto-director/runs/${run.id}`).then(setRun).catch(() => undefined); }, 2000); return () => window.clearInterval(timer); }, [params.id, run?.id, run?.status]);
  useEffect(() => { const id = [...(run?.steps || [])].reverse().find((step) => step.stage === "CHAPTER_EXECUTION" && step.status === "COMMITTED")?.output_artifact_id; if (id) void api(`/projects/${params.id}/writer-drafts/${id}`).then((value: unknown) => setDraft(value as Record<string, any>)).catch(() => undefined); }, [params.id, run?.steps]);
  useEffect(() => { if (!run?.current_chapter_id) return; void api(`/projects/${params.id}/chapters/${run.current_chapter_id}/quality`).then((value: unknown) => setQuality(value as Record<string, any>)).catch(() => undefined); void api(`/projects/${params.id}/chapters/${run.current_chapter_id}/planning-task`).then((value: any) => setTask(value?.task || value)).catch(() => undefined); }, [params.id, run?.current_chapter_id, run?.current_stage]);
  async function action(name: string, body?: unknown) { if (!run) return; setBusy(true); setError(""); try { const next = await api(`/projects/${params.id}/auto-director/runs/${run.id}/${name}`, { method: "POST", body: body ? JSON.stringify(body) : undefined }) as Run; setRun(next); if (name === "takeover") window.location.href = `/projects/${params.id}/director`; } catch (reason: unknown) { setError(reason instanceof ApiError ? reason.message : "操作失败"); } finally { setBusy(false); } }
  const directions = (run?.context?.directions || []) as Array<Record<string, any>>; const selectedDirection = run?.context?.selected_direction as Record<string, any> | undefined;
  const currentStep = run?.steps?.find((step) => step.stage === run.current_stage);
  const draftStep = [...(run?.steps || [])].reverse().find((step) => step.stage === "CHAPTER_EXECUTION" && step.status === "COMMITTED");
  const displayedChapter = run?.status === "COMPLETED" ? (run.context?.last_adopted_chapter_number || run.context?.current_chapter_number || 1) : (run?.context?.current_chapter_number || 1);
  return <main className="stack"><header className="page-header"><div><p className="eyebrow">AUTO DIRECTOR · LOCAL</p><h1>自动导演</h1><p>从方向确认推进到第一章检查点，所有关键结果都会保存在本地。</p></div><div className="row"><button className="secondary" onClick={() => action("pause")} disabled={busy || run?.status !== "RUNNING"}><Pause size={15} />暂停</button><button onClick={() => action("resume")} disabled={busy || run?.status !== "PAUSED"}><Play size={15} />继续</button></div></header>
    {error && <section className="section-card"><CircleAlert size={16} />{error}</section>}
    {!run ? <section className="section-card"><p>正在恢复最近的自动导演任务……</p></section> : <><section className="section-card"><div className="section-card-header"><div><p className="eyebrow">CURRENT CHECKPOINT</p><h2>{labels[run.current_stage] || run.current_stage}</h2></div><strong>{labels[run.status] || run.status}</strong></div><p>{run.next_action || "系统正在准备下一步。"}</p>{run.pause_reason && <p className="muted">暂停原因：{run.pause_reason}</p>}<div className="run-metrics"><span>当前章节：第 {run.context?.current_chapter_number || 1} 章</span><span>已完成：{(run.context?.completed_chapters as unknown[] | undefined)?.length || 0} 章</span><span>自动采用：{run.context?.adopted_chapters || 0} 次</span><span>当前阶段 token：{currentStep?.usage_metrics?.total_tokens || currentStep?.token_usage?.total_tokens || currentStep?.token_usage?.tokens || 0}</span><span>累计 token：{run.usage_metrics?.total_tokens || run.token_usage?.total_tokens || 0}</span><span>输入/输出：{run.usage_metrics?.prompt_tokens || 0} / {run.usage_metrics?.completion_tokens || 0}</span><span>调用次数：{run.usage_metrics?.calls || run.token_usage?.total_calls || 0}</span><span>失败/重试：{run.steps.filter((step) => ["FAILED", "BLOCKED"].includes(step.status)).length}</span><span>估算成本：{run.usage_metrics?.cost_status === "UNKNOWN" ? "未知" : (run.usage_metrics?.estimated_cost || "-")}</span></div></section>
      <section className="section-card"><p className="eyebrow">STAGE TIMELINE</p><div className="stage-timeline">{stages.map((stage) => { const done = run.steps.some((step) => step.stage === stage && step.status === "COMMITTED"); const active = stage === run.current_stage; return <div className={`stage-item ${done ? "done" : ""} ${active ? "active" : ""}`} key={stage}><span>{done ? <Check size={13} /> : active ? "●" : "○"}</span><small>{labels[stage]}</small></div>; })}</div></section>
      {selectedDirection && <section className="section-card"><div className="section-card-header"><div><p className="eyebrow">AUTO SELECTED DIRECTION</p><h2>{selectedDirection.title || "已选方向"}</h2></div><span className="status-badge"><Check size={13} />自动选择</span></div><p>{selectedDirection.selling_point || selectedDirection.premise}</p><div className="run-metrics"><span>结构评分：{run.context?.direction_score ?? "-"}</span><span>验证：{run.context?.direction_validation_report?.valid ? "通过" : "有质量债务"}</span></div><button className="secondary" type="button" onClick={() => setDirectionOpen((value) => !value)}><Eye size={14} />{directionOpen ? "收起方向详情" : "查看方向详情"}</button>{directionOpen && <div className="direction-detail"><p><strong>主角目标：</strong>{selectedDirection.protagonist?.desire || "未设置"}</p><p><strong>核心冲突：</strong>{selectedDirection.core_conflict || "未设置"}</p><p><strong>前十章承诺：</strong>{(selectedDirection.first_ten_chapter_promises || []).join("、") || "未设置"}</p><p><strong>世界边界：</strong>{(selectedDirection.world_boundaries || []).join("、") || "未设置"}</p><p><strong>文风建议：</strong>{selectedDirection.style_advice || "未设置"}</p></div>}</section>}
      {draftStep && <section className="section-card"><p className="eyebrow">CURRENT CHAPTER</p><h2>第 {displayedChapter} 章</h2><p>草稿引用：{draftStep.output_artifact_id}</p>{task && <div className="run-metrics"><span>章节任务：{task.objective || "已生成"}</span><span>必须事件：{(task.must_events || []).length} 项</span><span>场景节拍：{(task.scene_beats || []).length} 项</span></div>}{quality?.current_assessment && <div className="quality-summary"><strong>质量审核：{quality.current_assessment.status}</strong><span>得分：{quality.current_assessment.overall_score ?? "待定"}</span><small>{(quality.current_assessment.decision_reason_codes || []).join("、") || "未发现阻塞问题"}</small></div>}{(run.context?.quality_debts as string[] | undefined)?.length ? <p className="muted">质量债务：{(run.context?.quality_debts as string[]).join("、")}</p> : null}{draft?.content && <article className="prose-preview">{draft.content}</article>}{run.status !== "COMPLETED" && <div className="row"><button className="secondary" onClick={() => action("retry")} disabled={busy}><RotateCcw size={15} />重试当前阶段</button><button className="secondary" onClick={() => action("takeover")} disabled={busy}><UserRoundCog size={15} />接管编辑</button></div>}{run.status === "COMPLETED" && <p className="success-note">整本自动导演已完成。</p>}</section>}
      {chapters.length > 0 && <section className="section-card"><div className="section-card-header"><div><p className="eyebrow">COMPLETED CHAPTERS</p><h2>{run.status === "COMPLETED" ? "整本自动导演已完成" : "已完成章节"}</h2></div><Link className="button secondary" href={`/projects/${params.id}/chapters`}>查看章节列表</Link></div><div className="run-metrics"><span>总章节数：{run.settings?.target_chapters || chapters.length}</span><span>已完成章节：{(run.context?.completed_chapters as unknown[] | undefined)?.length || 0}</span><span>最近章节：第 {run.context?.last_adopted_chapter_number || displayedChapter} 章</span></div><div className="completed-chapters">{chapters.filter((chapter) => (run.context?.completed_chapters as unknown[] | undefined)?.includes(chapter.number)).map((chapter) => <Link key={chapter.id} href={`/projects/${params.id}/chapters?chapter=${chapter.id}`}><strong>第 {chapter.number} 章</strong><span>{chapter.title || "未命名章节"}</span></Link>)}</div></section>}
      {currentStep?.error_summary && <section className="section-card"><h2>需要处理</h2><p>{currentStep.error_summary}</p><button onClick={() => action("retry")} disabled={busy}><RotateCcw size={15} />重试</button></section>}
    </>}</main>;
}
