"use client";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Plus, Search, X } from "lucide-react";
import { toast } from "sonner";
import { api, ApiError } from "../../app/lib";
import { DeveloperData, EmptyState, ErrorState, LoadingState, PageHeader, SectionCard, StatusBadge } from "../ui/primitives";

type Spec = { title: string; description: string; endpoint: string; fields: { key: string; label: string; type?: "text" | "textarea" | "select" | "number"; options?: string[]; required?: boolean }[]; itemTitle: (item: any) => string; itemMeta: (item: any) => string[] };
const specs: Record<string, Spec> = {
  characters: { title:"人物档案", description:"管理世界中的行动者、其当前目标与状态。", endpoint:"characters", fields:[{key:"name",label:"人物名称",required:true},{key:"profile",label:"人物简介",type:"textarea"},{key:"goals",label:"当前目标",type:"textarea"},{key:"active",label:"状态",type:"select",options:["true","false"]}], itemTitle:i=>i.name, itemMeta:i=>[i.current_state?.location_id ? `位置：${i.current_state.location_id}` : "位置尚未设定", i.goals?.current ? `目标：${i.goals.current}` : "当前目标尚未设定"] },
  "world-entities": { title:"世界实体", description:"地点、组织、物品与其他构成世界的实体。", endpoint:"world-entities", fields:[{key:"name",label:"实体名称",required:true},{key:"entity_type",label:"实体类型",type:"select",options:["CITY","LOCATION","SECT","FACTION","COUNTRY","ITEM","SYSTEM","HISTORY","CUSTOM"],required:true},{key:"profile",label:"基础描述",type:"textarea"},{key:"active",label:"状态",type:"select",options:["true","false"]}], itemTitle:i=>i.name, itemMeta:i=>[i.entity_type || "CUSTOM", i.active === false ? "已停用" : "可用"] },
  canon: { title:"世界事实", description:"世界事实（Canon）是所有后续裁定与排演可依赖的真实设定。", endpoint:"canon", fields:[{key:"proposition",label:"事实陈述",type:"textarea",required:true},{key:"fact_type",label:"事实类型",type:"select",options:["WORLD_FACT","CORE_CANON","SECRET_CANON","TEMPORARY"],required:true},{key:"locked",label:"锁定状态",type:"select",options:["false","true"]},{key:"data",label:"结构化补充",type:"textarea"}], itemTitle:i=>i.proposition, itemMeta:i=>[i.fact_type, i.locked ? "已锁定" : "可编辑"] },
  "story-threads": { title:"剧情线程", description:"追踪正在推进的冲突、目标与未解问题。", endpoint:"story-threads", fields:[{key:"title",label:"线程标题",required:true},{key:"type",label:"线程类型",required:true},{key:"goal",label:"当前目标",type:"textarea"},{key:"weight",label:"权重",type:"number"}], itemTitle:i=>i.title, itemMeta:i=>[i.type, `进度 ${Math.round((i.progress || 0) * 100)}%`] },
  "writing-bibles": { title:"写作手册", description:"定义叙事风格与写作约束。", endpoint:"writing-bibles", fields:[{key:"version",label:"版本",type:"number",required:true},{key:"rules",label:"规则说明",type:"textarea"},{key:"active",label:"立即启用",type:"select",options:["true","false"]}], itemTitle:i=>`版本 ${i.version}`, itemMeta:i=>[i.active ? "当前启用" : "未启用"] },
  "anti-ai-bibles": { title:"反 AI 规则", description:"为未来写作系统提供可审计的表达与风险限制。", endpoint:"anti-ai-bibles", fields:[{key:"version",label:"版本",type:"number",required:true},{key:"writing_principles",label:"写作原则",type:"textarea"},{key:"active",label:"立即启用",type:"select",options:["true","false"]}], itemTitle:i=>`版本 ${i.version}`, itemMeta:i=>[i.active ? "当前启用" : "未启用"] },
};
function parseValue(key: string, value: string) { if (["profile","goals","data","rules"].includes(key)) return value.trim() ? { description:value } : {}; if (key === "writing_principles") return value.trim() ? value.split("\n").filter(Boolean) : []; if (key === "active" || key === "locked") return value === "true"; if (key === "version" || key === "weight") return Number(value); return value; }

export function ResourceWorkspace({ projectId, resource }: { projectId: string; resource: string }) {
  const spec = specs[resource];
  if (!spec) return <EmptyState title="页面尚未开放" description="该资源尚未提供普通工作台界面。" />;
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [search, setSearch] = useState("");
  const schema = useMemo(() => z.object(Object.fromEntries(spec.fields.map((field) => [field.key, field.required ? z.string().min(1, "请填写此字段") : z.string().optional()]))), [spec]);
  const form = useForm<any>({ resolver:zodResolver(schema), defaultValues:Object.fromEntries(spec.fields.map(field => [field.key, field.key === "entity_type" ? "CUSTOM" : field.key === "fact_type" ? "WORLD_FACT" : field.key === "active" ? "true" : field.key === "locked" ? "false" : field.key === "version" ? "1" : field.key === "weight" ? "1" : ""])) });
  const query = useQuery({ queryKey:["resource",projectId,spec.endpoint], queryFn:() => api(`/projects/${projectId}/${spec.endpoint}`) as Promise<any[]> });
  const create = useMutation({
    mutationFn: (value: any) => api(`/projects/${projectId}/${spec.endpoint}`, { method: "POST", body: JSON.stringify(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, parseValue(key, String(item))]))) }),
    onSuccess: () => { toast.success(`${spec.title}创建成功`); queryClient.invalidateQueries({ queryKey: ["resource", projectId, spec.endpoint] }); setOpen(false); form.reset(); },
    onError: (error: Error) => toast.error(`创建失败：${error.message}`),
  });
  if (query.isLoading) return <LoadingState />; if (query.isError) return <ErrorState message={(query.error as ApiError).message || "加载失败"} retry={() => query.refetch()} />;
  const items = (query.data || []).filter((item:any) => `${spec.itemTitle(item)} ${spec.itemMeta(item).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader title={spec.title} description={spec.description} action={<button onClick={() => setOpen(true)}><Plus size={16} /> 新建</button>} /><SectionCard><div className="resource-toolbar"><div className="search-box"><Search size={16} /><input className="search-input" value={search} onChange={event => setSearch(event.target.value)} placeholder={`搜索${spec.title}`} /></div><span className="muted">共 {items.length} 条</span></div>{items.length === 0 ? <EmptyState title={`还没有${spec.title}`} description="创建第一条信息，让世界拥有可被裁定的基础。" /> : <div className="resource-list">{items.map((item:any) => <article className="resource-row" key={item.id}><div><div className="resource-title">{spec.itemTitle(item)}</div><small>{spec.itemMeta(item)[1] || ""}</small></div><span>{spec.itemMeta(item)[0]}</span><StatusBadge value={item.status || (item.active === false ? "停用" : item.locked ? "锁定" : "可用")} /><div className="actions"><details><summary>详情</summary><DeveloperData value={item} /></details></div></article>)}</div>}</SectionCard>{open && <div className="dialog-backdrop"><form className="dialog" onSubmit={form.handleSubmit(values => create.mutate(values))}><header><h2>新建{spec.title}</h2><button className="secondary" type="button" onClick={() => setOpen(false)}><X size={16} /></button></header><div className="form-grid">{spec.fields.map(field => <label className={`field ${field.type === "textarea" ? "full" : ""}`} key={field.key}><span>{field.label}</span>{field.type === "textarea" ? <textarea {...form.register(field.key)} /> : field.type === "select" ? <select {...form.register(field.key)}>{field.options?.map(option => <option key={option} value={option}>{option === "true" ? "是" : option === "false" ? "否" : option}</option>)}</select> : <input type={field.type || "text"} {...form.register(field.key)} />}{form.formState.errors[field.key] && <small className="field-error">{String(form.formState.errors[field.key]?.message)}</small>}</label>)}</div><footer><button className="secondary" type="button" onClick={() => setOpen(false)}>取消</button><button disabled={create.isPending}>{create.isPending ? "正在保存…" : "创建"}</button></footer></form></div>}</>;
}
