"use client";

import { useEffect, useState } from "react";
import { Pause, Play, PlayCircle, RotateCcw } from "lucide-react";
import { api, ApiError } from "../../../lib";
import { EmptyState, ErrorState, PageHeader, SectionCard, StatusBadge } from "../../../../components/ui/primitives";

type AutonomyRun = { id: string; status: string; scene_budget: number; committed_scene_count?: number; stop_reason?: string; active?: boolean };

export default function WorldRunPage({ params }: { params: { id: string } }) {
  const [run, setRun] = useState<AutonomyRun>(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = () => { void api(`/projects/${params.id}/autonomy/runs`).then((items) => setRun((items as AutonomyRun[]).find((item) => item.active || ["RUNNING", "PAUSED"].includes(item.status)))).catch((reason: unknown) => setError(reason instanceof ApiError ? reason.message : "无法读取世界运行状态。")); };
  useEffect(() => { load(); }, [params.id]);
  async function create() { setBusy(true); setError(""); try { const next = await api(`/projects/${params.id}/autonomy/runs`, { method: "POST", body: JSON.stringify({ scene_budget: 3, max_turns_per_scene: 6, performance_mode: "HEURISTIC", resolver_mode: "HEURISTIC", idempotency_key: `ui-${Date.now()}` }) }) as AutonomyRun; setRun(next); setMessage("世界运行已创建，可以开始推进第一场。 "); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "无法创建世界运行。 "); } finally { setBusy(false); } }
  async function action(kind: "advance" | "pause" | "resume") { if (!run) return; setBusy(true); setError(""); try { const next = kind === "advance" ? (await api(`/projects/${params.id}/autonomy/runs/${run.id}/advance`, { method: "POST", body: JSON.stringify({ max_scenes: 1, idempotency_key: `ui-${run.id}` }) }) as { run: AutonomyRun }).run : await api(`/projects/${params.id}/autonomy/runs/${run.id}/${kind}`, { method: "POST", body: kind === "pause" ? JSON.stringify({ reason: "USER_PAUSED" }) : undefined }) as AutonomyRun; setRun(next); setMessage(kind === "advance" ? "已推进一场并更新正式世界。" : kind === "pause" ? "世界运行已暂停。" : "世界运行已恢复。"); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "运行操作失败。 "); } finally { setBusy(false); } }
  return <main className="stack"><PageHeader title="世界运行" description="在已审批的章节任务边界内推进正式场景。这里的每次推进都会写入世界历史。" action={run ? <StatusBadge value={run.status} /> : undefined} />{error && <ErrorState message={error} retry={() => { setError(""); load(); }} />}{message && <div className="success-state">{message}</div>}{!run ? <SectionCard title="尚未创建世界运行" description="创建后，系统会按场景预算推进正式世界；没有审批和锁定的章节任务时会安全停止。"><button onClick={() => void create()} disabled={busy}><PlayCircle size={16} />{busy ? "正在创建…" : "创建世界运行"}</button></SectionCard> : <><SectionCard title="运行进度" aside={<StatusBadge value={run.status} />}><div className="run-metrics"><span>已提交场景：{run.committed_scene_count || 0}</span><span>场景预算：{run.scene_budget}</span></div><p className="muted">{run.stop_reason || "运行边界由章节任务和连续性验证控制。"}</p><div className="row"><button onClick={() => void action("advance")} disabled={busy || run.status !== "RUNNING"}><Play size={15} />推进一场</button>{run.status === "RUNNING" ? <button className="secondary" onClick={() => void action("pause")} disabled={busy}><Pause size={15} />暂停</button> : run.status === "PAUSED" ? <button className="secondary" onClick={() => void action("resume")} disabled={busy}><RotateCcw size={15} />恢复</button> : null}</div></SectionCard><EmptyState title="等待推进" description="推进后会在这里显示已提交场景；可从导演台先推演候选方案。" /></>}</main>;
}
