"use client";

import { useEffect, useState } from "react";
import { Lock, Pause, Play, RotateCcw, Send } from "lucide-react";
import { api, ApiError } from "../../../../lib";
import { ErrorState, PageHeader, SectionCard, StatusBadge } from "../../../../../components/ui/primitives";

type Volume = { id: string; volume_number: number; title?: string; status: string; volume_goal?: string; core_conflict?: string; progress?: Record<string, any>; windows?: Array<Record<string, any>> };
export default function VolumeDirectorPage({ params, searchParams }: { params: { id: string }; searchParams?: { volume?: string } }) {
  const [volume, setVolume] = useState<Volume>(); const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => { void api(`/projects/${params.id}/volumes`).then((items: unknown) => { const volumes = items as Volume[]; setVolume(volumes.find((item) => item.id === searchParams?.volume) || volumes[0]); }).catch((reason: unknown) => setError(reason instanceof ApiError ? reason.message : "无法读取当前卷")); };
  useEffect(load, [params.id, searchParams?.volume]);
  async function action(path: string, body?: unknown) { if (!volume) return; setBusy(true); try { await api(`/projects/${params.id}/volumes/${volume.id}/${path}`, { method: "POST", body: body ? JSON.stringify(body) : undefined }); setMessage("操作已保存"); load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "操作失败"); } finally { setBusy(false); } }
  async function guidance() { if (!volume || !note.trim()) return; await action("guidance", { author_note: note, affected_scope: "WINDOW", requires_replan: false }); setNote(""); }
  if (!volume) return <main className="stack"><PageHeader title="当前卷导演" description="正在读取卷级检查点。" /></main>;
  const progress = volume.progress || {};
  return <main className="stack"><PageHeader title={`第 ${volume.volume_number} 卷导演台`} description="作者掌握书籍合同、剧情走向和封卷决定；AI 只推进当前窗口和未写内容。" action={<StatusBadge value={volume.status} />} />{error && <ErrorState message={error} retry={() => { setError(""); load(); }} />}{message && <div className="success-state">{message}</div>}<SectionCard title="当前卷合同"><div className="task-summary"><div><small>卷目标</small><p>{volume.volume_goal || "未设置"}</p></div><div><small>核心冲突</small><p>{volume.core_conflict || "未设置"}</p></div><div><small>目标进度</small><p>{Math.round((progress.volume_goal_progress || 0) * 100)}%</p></div><div><small>完成判断</small><p>{progress.should_prepare_seal ? "可以提出封存建议" : "尚未满足封存条件，继续当前卷"}</p></div></div></SectionCard><SectionCard title="当前章节窗口" description="窗口最多 10 章，结束不等于本卷结束。">{(volume.windows || []).map((window) => <div className="section-heading" key={window.id}><span>第 {window.start_chapter_number}-{window.end_chapter_number} 章 · {window.status}</span><span className="muted">已生成 {window.actual_generated_count || 0} 章</span></div>)}<div className="row"><button onClick={() => void action("continue")} disabled={busy}><Play size={15} />继续</button><button className="secondary" onClick={() => void action("pause", { reason: "作者暂停当前卷" })} disabled={busy}><Pause size={15} />暂停</button></div></SectionCard><SectionCard title="作者指导"><textarea className="field full" value={note} onChange={(event) => setNote(event.target.value)} placeholder="告诉 AI 当前窗口要强调什么；已采用正文和封存卷不会被重写。" /><div className="row"><button onClick={() => void guidance()} disabled={busy || !note.trim()}><Send size={15} />提交指导</button><button className="secondary" onClick={() => void action("seal", { author_confirmed: true })} disabled={busy || !progress.should_prepare_seal}><Lock size={15} />确认封存本卷</button><button className="secondary" onClick={() => void action("unseal", { reason: "作者要求重新规划" })} disabled={busy || volume.status !== "SEALED"}><RotateCcw size={15} />解封</button></div></SectionCard></main>;
}
