"use client";
import { useEffect, useState } from "react";
import { api } from "../../../../lib";

type Candidate = { id: string; candidate_type: string; status: string; initial_error_code?: string; current_version_number: number; source_trace_id: string; context_locator: Record<string, unknown>; adopted_resource_type?: string; adopted_resource_id?: string };
type Version = { id: string; version_number: number; origin: string; parent_version_id?: string; schema_valid: boolean; constraint_valid: boolean; payload_fingerprint: string; payload: unknown; validation_report: unknown };
type RecoveryCandidateResponse = { candidate: Candidate; current_version: Version; available_actions: string[]; validation_report: unknown };

export default function RecoveryCandidateDetail({ params }: { params: { id: string; candidateId: string } }) {
  const [data, setData] = useState<RecoveryCandidateResponse>(); const [versions, setVersions] = useState<Version[]>([]); const [patches, setPatches] = useState("[{\n  \"operation\": \"SET\",\n  \"path\": \"/decision_summary\",\n  \"value\": \"\"\n}]"); const [error, setError] = useState<string>();
  const load = () => Promise.all([api(`/projects/${params.id}/recovery-candidates/${params.candidateId}`), api(`/projects/${params.id}/recovery-candidates/${params.candidateId}/versions`)]).then(([candidate, history]) => { setData(candidate); setVersions(history); }).catch((e) => setError(e.message));
  useEffect(() => { void load(); }, [params.id, params.candidateId]);
  async function act(kind: string) { try { const body = kind === "edit" ? { base_version: data!.candidate.current_version_number, changes: JSON.parse(patches) } : undefined; if (kind === "adopt" && !window.confirm("Adopt 会把当前已验证 Candidate 应用到对应的 rehearsal artifact，但不会直接修改正式 Canon。")) return; await api(`/projects/${params.id}/recovery-candidates/${params.candidateId}/${kind}`, { method: "POST", body: body ? JSON.stringify(body) : undefined }); await load(); } catch (e: any) { setError(e.message); } }
  if (!data) return <main className="stack"><p>加载候选中...</p>{error && <p>{error}</p>}</main>;
  const { candidate, current_version: currentVersion, available_actions: actions } = data; const worldMissing = actions.includes("EDIT_WORLD");
  return <main className="stack"><section><h1>{candidate.candidate_type}</h1><p>状态：{candidate.status} · 初始错误：{candidate.initial_error_code || "-"}</p><p>当前版本：{candidate.current_version_number} · 来源 Trace：{candidate.source_trace_id}</p><p>Schema valid：{String(currentVersion.schema_valid)} · Constraint valid：{String(currentVersion.constraint_valid)}</p><p>Context locator：<code>{JSON.stringify(candidate.context_locator)}</code></p>{candidate.adopted_resource_id && <p>Adopted resource: {candidate.adopted_resource_type} / {candidate.adopted_resource_id}</p>}<p className="muted">这里只是在修改候选结果，不会直接修改正式世界。</p></section>{worldMissing && <section className="panel"><p>补充所缺世界事实后，重新执行来源流程。</p><a href={`/projects/${params.id}/canon`}>Edit World</a></section>}<section className="panel"><h2>当前候选</h2><pre>{JSON.stringify(currentVersion.payload, null, 2)}</pre><pre>{JSON.stringify(data.validation_report, null, 2)}</pre></section>{actions.includes("MANUAL_EDIT") && !worldMissing && <section className="panel"><h2>Manual Edit</h2><textarea value={patches} onChange={(e) => setPatches(e.target.value)} rows={10} /><button onClick={() => act("edit")}>保存候选修改</button></section>}<section className="panel"><h2>Version History</h2>{versions.map((v) => <details key={v.id}><summary>v{v.version_number} · {v.origin} · schema={String(v.schema_valid)} · constraint={String(v.constraint_valid)}</summary><p>Parent: {v.parent_version_id || "-"}</p><p>Fingerprint: {v.payload_fingerprint}</p><pre>{JSON.stringify(v.payload, null, 2)}</pre><pre>{JSON.stringify(v.validation_report, null, 2)}</pre></details>)}</section><section className="stack">{actions.includes("AI_REPAIR") && !worldMissing && <button onClick={() => act("ai-repair")}>AI Repair</button>}{actions.includes("ADOPT") && !worldMissing && <button onClick={() => act("adopt")}>Adopt</button>}{actions.includes("ABORT") && <button onClick={() => act("abort")}>Abort</button>}</section>{error && <p>{error}</p>}</main>;
}
