"use client";
import { useEffect, useState } from "react";
import { api } from "../../../../lib";
import { term } from "../../../../terminology";

type Candidate = { id: string; candidate_type: string; status: string; initial_error_code?: string; current_version_number: number; source_trace_id: string; context_locator: Record<string, unknown>; adopted_resource_type?: string; adopted_resource_id?: string };
type Version = { id: string; version_number: number; origin: string; parent_version_id?: string; schema_valid: boolean; constraint_valid: boolean; payload_fingerprint: string; payload: unknown; validation_report: unknown };
type RecoveryCandidateResponse = { candidate: Candidate; current_version: Version; available_actions: string[]; validation_report: unknown };

export default function RecoveryCandidateDetail({ params }: { params: { id: string; candidateId: string } }) {
  const [data, setData] = useState<RecoveryCandidateResponse>(); const [versions, setVersions] = useState<Version[]>([]); const [patches, setPatches] = useState("[{\n  \"operation\": \"SET\",\n  \"path\": \"/decision_summary\",\n  \"value\": \"\"\n}]"); const [error, setError] = useState<string>();
  const load = () => Promise.all([api(`/projects/${params.id}/recovery-candidates/${params.candidateId}`), api(`/projects/${params.id}/recovery-candidates/${params.candidateId}/versions`)]).then(([candidate, history]) => { setData(candidate); setVersions(history); }).catch((e) => setError(e.message));
  useEffect(() => { void load(); }, [params.id, params.candidateId]);
  async function act(kind: string) { try { const body = kind === "edit" ? { base_version: data!.candidate.current_version_number, changes: JSON.parse(patches) } : undefined; if (kind === "adopt" && !window.confirm("Adopt 会把当前已验证 Candidate 应用到对应的 rehearsal artifact，但不会直接修改正式 Canon。")) return; await api(`/projects/${params.id}/recovery-candidates/${params.candidateId}/${kind}`, { method: "POST", body: body ? JSON.stringify(body) : undefined }); await load(); } catch (e: any) { setError(e.message); } }
  if (!data) return <main className="stack"><p>加载候选中...</p>{error && <p>{error}</p>}</main>;
  const { candidate, current_version: currentVersion, available_actions: actions } = data; const worldMissing = actions.includes("EDIT_WORLD");
  return <main className="stack"><section><h1>{term(candidate.candidate_type)}</h1><p>状态：{term(candidate.status)} · 初始错误：{term(candidate.initial_error_code)}</p><p>当前版本：{candidate.current_version_number} · 来源追踪：{candidate.source_trace_id}</p><p>结构校验：{currentVersion.schema_valid ? "通过" : "未通过"} · 约束校验：{currentVersion.constraint_valid ? "通过" : "未通过"}</p>{candidate.adopted_resource_id && <p>已采用资源：{candidate.adopted_resource_type} / {candidate.adopted_resource_id}</p>}<p className="muted">这里只是在修改候选结果，不会直接修改正式世界。</p></section>{worldMissing && <section className="panel"><p>补充所缺世界事实后，重新执行来源流程。</p><a className="button secondary" href={`/projects/${params.id}/canon`}>补充世界事实</a></section>}<section className="panel"><h2>当前候选</h2><pre>{JSON.stringify(currentVersion.payload, null, 2)}</pre><details className="developer-data"><summary>验证与定位数据</summary><pre>{JSON.stringify({ validation_report:data.validation_report, context_locator:candidate.context_locator }, null, 2)}</pre></details></section>{actions.includes("MANUAL_EDIT") && !worldMissing && <section className="panel"><h2>手动修改</h2><textarea value={patches} onChange={(e) => setPatches(e.target.value)} rows={10} /><button onClick={() => act("edit")}>保存候选修改</button></section>}<section className="panel"><h2>版本历史</h2>{versions.map((v) => <details key={v.id}><summary>v{v.version_number} · {term(v.origin)} · 结构={v.schema_valid ? "通过" : "未通过"} · 约束={v.constraint_valid ? "通过" : "未通过"}</summary><p>父版本：{v.parent_version_id || "-"}</p><p>指纹：{v.payload_fingerprint}</p><pre>{JSON.stringify(v.payload, null, 2)}</pre><pre>{JSON.stringify(v.validation_report, null, 2)}</pre></details>)}</section><section className="stack">{actions.includes("AI_REPAIR") && !worldMissing && <button onClick={() => act("ai-repair")}>AI 修复</button>}{actions.includes("ADOPT") && !worldMissing && <button onClick={() => act("adopt")}>采用</button>}{actions.includes("ABORT") && <button className="secondary" onClick={() => act("abort")}>放弃</button>}</section>{error && <p>{error}</p>}</main>;
}
