"use client";
import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { api, ApiError } from "../../app/lib";
import { displayStatus, term } from "../../app/terminology";
import { EmptyState, ErrorState, LoadingState, PageHeader, SectionCard, StatusBadge } from "../ui/primitives";

export function RetconWorkspace({ projectId }: { projectId: string }) {
  const client=useQueryClient(); const [open,setOpen]=useState(false); const [revisionId,setRevisionId]=useState(""); const [reason,setReason]=useState("");
  const revisions=useQuery({queryKey:["revisions",projectId],queryFn:()=>api(`/projects/${projectId}/revisions`) as Promise<any[]>}); const requests=useQuery({queryKey:["retcon-requests",projectId],queryFn:()=>api(`/projects/${projectId}/retcon/requests`) as Promise<any[]>});
  const create=useMutation({mutationFn:()=>api(`/projects/${projectId}/retcon/requests`,{method:"POST",body:JSON.stringify({source_revision_id:revisionId,reason})}),onSuccess:()=>{toast.success("历史改写请求已创建");setOpen(false);client.invalidateQueries({queryKey:["retcon-requests",projectId]})},onError:(e:Error)=>toast.error(`创建失败：${e.message}`)}); const analyze=useMutation({mutationFn:(id:string)=>api(`/projects/${projectId}/retcon/requests/${id}/analyze`,{method:"POST"}),onSuccess:()=>{toast.success("影响分析完成");client.invalidateQueries({queryKey:["retcon-requests",projectId]})},onError:(e:Error)=>toast.error(`分析失败：${(e as ApiError).message||e.message}`)}); const abort=useMutation({mutationFn:(id:string)=>api(`/projects/${projectId}/retcon/requests/${id}/abort`,{method:"POST"}),onSuccess:()=>{toast.success("已放弃历史改写");client.invalidateQueries({queryKey:["retcon-requests",projectId]})}});
  if(revisions.isLoading||requests.isLoading)return <LoadingState/>; if(revisions.isError||requests.isError)return <ErrorState message="暂时无法读取历史改写数据。" retry={()=>{void revisions.refetch();void requests.refetch()}}/>;
  return <main className="stack"><PageHeader title="历史改写" description="预览修改世界事实后会影响哪些历史。" action={<button onClick={()=>setOpen(true)}><Plus size={15}/> 新建影响分析</button>}/><section className="preview-warning"><ShieldCheck size={18}/><span><strong>当前只是影响预览。</strong> 分析不会修改世界事实、人物认知、记忆或历史场景。</span></section><SectionCard title="历史改写请求"><div className="resource-list">{requests.data?.length?requests.data.map(item=>{const actions=item.available_actions||[];const stale=item.effective_status==="STALE";return <article className="resource-row" key={item.id}><div><div className="resource-title">{stale?"计划已过期":item.latest_plan?.earliest_affected_sequence?`从场景 ${item.latest_plan.earliest_affected_sequence} 起`:"待分析的世界修改"}</div><small>{item.reason}</small></div><span>计划 v{item.current_plan_version||0}</span><StatusBadge value={displayStatus(item.effective_status||item.status)}/><div className="actions">{item.latest_plan&&<Link className="button secondary" href={`/projects/${projectId}/retcon/plans/${item.latest_plan.id}`}>查看影响</Link>}{actions.includes("ANALYZE")&&<button onClick={()=>analyze.mutate(item.id)}>开始分析</button>}{actions.includes("REANALYZE")&&<button onClick={()=>analyze.mutate(item.id)}>重新分析</button>}{actions.includes("ABORT")&&<button className="secondary" onClick={()=>abort.mutate(item.id)}>放弃修改</button>}</div></article>}) : <EmptyState title="还没有历史改写请求" description="从已完成预览的世界修订开始，生成一份可审计的因果影响计划。"/>}</div></SectionCard>{open&&<div className="dialog-backdrop"><form className="dialog" onSubmit={e=>{e.preventDefault();create.mutate()}}><header><h2>新建历史改写</h2><button className="secondary" type="button" onClick={()=>setOpen(false)}>×</button></header><label className="field"><span>选择已预览的世界修订</span><select required value={revisionId} onChange={e=>setRevisionId(e.target.value)}><option value="">请选择修订</option>{revisions.data?.filter(item=>item.status==="PREVIEWED").map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label className="field"><span>修改原因</span><textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="说明为什么需要重新审视这段历史"/></label><footer><button className="secondary" type="button" onClick={()=>setOpen(false)}>取消</button><button disabled={!revisionId||!reason}>创建请求</button></footer></form></div>}</main>;
}

export function RetconPlanView({projectId,planId}:{projectId:string;planId:string}){
  const client=useQueryClient(); const query=useQuery({queryKey:["retcon-plan",planId],queryFn:()=>api(`/projects/${projectId}/retcon/plans/${planId}`) as Promise<any>}); const apply=useMutation({mutationFn:()=>api(`/projects/${projectId}/retcon/requests/${query.data.plan.retcon_request_id}/apply`,{method:"POST",body:JSON.stringify({plan_id:planId,explicit_confirmation:true,author_override:true,author_override_reason:"作者确认历史改写"})}),onSuccess:()=>{toast.success("历史修改已应用，等待历史重演");client.invalidateQueries({queryKey:["retcon-plan",planId]})},onError:(e:Error)=>toast.error(`应用失败：${(e as ApiError).message||e.message}`)}); if(query.isLoading)return <LoadingState/>; if(query.isError)return <ErrorState message="暂时无法读取影响计划。" retry={()=>void query.refetch()}/>;
  const plan=query.data.plan;const items=query.data.items||[];const grouped=(c:string)=>items.filter((i:any)=>i.classification===c);const classes=[["REPLAY_REQUIRED","需要重新演出"],["REBUILD_COGNITION","需要重建认知"],["REVALIDATE","需要重新验证"],["INVALIDATED","修改后将失效"]];
  const ranges=plan.impact_summary?.preserved_scene_ranges||[];
  const canApply=plan.status==="READY"&&!plan.is_stale&&!items.some((item:any)=>item.classification==="REVALIDATE")&&!plan.validation_report?.issues?.some((issue:any)=>issue.severity==="BLOCKING");
  return <main className="stack"><PageHeader title="影响分析" description="这是一份历史依赖计划。应用前需要作者明确确认，应用后世界会暂停推进等待历史重演。" action={<span className="actions">{canApply&&<button onClick={()=>{if(window.confirm("应用后正式世界事实会发生变化，受影响认知将暂时失效并等待历史重演。确认应用？"))apply.mutate()}} disabled={apply.isPending}>应用历史修改</button>}<StatusBadge value={plan.status==="BLOCKED"?"分析被阻断":plan.is_stale?"计划已过期":canApply?"可以应用":"不可应用"}/></span>}/><section className="preview-warning"><ShieldCheck size={18}/><span><strong>作者确认后才会修改正式世界。</strong> 不会自动重演场景，也不会自动生成新的认知。</span></section>{plan.status==="BLOCKED"&&<section className="preview-warning"><strong>分析被阻断：</strong> {plan.validation_report?.issues?.filter((i:any)=>i.severity==="BLOCKING").map((i:any)=>i.message).join("；")||"无法生成可靠的影响计划。"}</section>}<section className="impact-summary"><div><small>最早受影响场景</small><strong>{plan.earliest_affected_sequence?`场景 ${plan.earliest_affected_sequence}`:"暂无明确边界"}</strong></div><div><small>需要重新演出</small><strong>{plan.impact_summary.replay_scene_count||0}</strong></div><div><small>可以保留</small><strong>{plan.impact_summary.preserved_scene_count||0}</strong></div></section>{ranges.length>0&&<SectionCard title="可以保留的历史"><p className="muted">共 {plan.impact_summary.preserved_scene_count} 个场景可以保留。</p>{ranges.map((r:any)=><div key={`${r.sequence_start}-${r.sequence_end}`}>场景 {r.sequence_start}{r.sequence_end!==r.sequence_start?`–${r.sequence_end}`:""}</div>)}</SectionCard>}{classes.map(([classification,title])=><SectionCard title={title} key={classification}>{grouped(classification).length?<div className="impact-list">{grouped(classification).map((item:any)=><article key={item.id}><strong>{term(item.resource_type)}</strong><p>{item.reason_summary}</p>{item.dependency_path?.length>1&&<div className="causal-path">{item.dependency_path.map((node:any,index:number)=><span key={`${node.id}-${index}`}>{term(node.type)}{index<item.dependency_path.length-1?" → ":""}</span>)}</div>}<details className="developer-data"><summary>开发者数据</summary><small>{item.reason_code} · {item.resource_id}</small></details></article>)}</div>:<p className="muted">没有该分类的影响对象。</p>}</SectionCard>)}<details className="developer-data"><summary>开发者数据</summary><pre>{JSON.stringify({plan,items},null,2)}</pre></details></main>;
}
