"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { History, Plus, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { api, ApiError } from "../../app/lib";
import { displayStatus, term } from "../../app/terminology";
import { EmptyState, ErrorState, LoadingState, PageHeader, SectionCard, StatusBadge } from "../ui/primitives";

export function RetconWorkspace({ projectId }: { projectId: string }) {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [revisionId, setRevisionId] = useState(""); const [reason, setReason] = useState("");
  const revisions = useQuery({ queryKey:["revisions", projectId], queryFn:() => api(`/projects/${projectId}/revisions`) as Promise<any[]> });
  const requests = useQuery({ queryKey:["retcon-requests", projectId], queryFn:() => api(`/projects/${projectId}/retcon/requests`) as Promise<any[]> });
  const create = useMutation({ mutationFn:() => api(`/projects/${projectId}/retcon/requests`, { method:"POST", body:JSON.stringify({ source_revision_id:revisionId, reason }) }), onSuccess:() => { toast.success("历史改写请求已创建"); setOpen(false); setReason(""); client.invalidateQueries({ queryKey:["retcon-requests", projectId] }); }, onError:(e:Error) => toast.error(`创建失败：${e.message}`) });
  const analyze = useMutation({ mutationFn:(id:string) => api(`/projects/${projectId}/retcon/requests/${id}/analyze`, { method:"POST" }), onSuccess:() => { toast.success("影响分析完成"); client.invalidateQueries({ queryKey:["retcon-requests", projectId] }); }, onError:(e:Error) => toast.error(`分析失败：${(e as ApiError).message || e.message}`) });
  if (revisions.isLoading || requests.isLoading) return <LoadingState />;
  if (revisions.isError || requests.isError) return <ErrorState message="暂时无法读取历史改写数据。" retry={() => { void revisions.refetch(); void requests.refetch(); }} />;
  return <main className="stack"><PageHeader title="历史改写" description="预览修改世界事实后会影响哪些历史。" action={<button onClick={() => setOpen(true)}><Plus size={15} /> 新建影响分析</button>} /><section className="preview-warning"><ShieldCheck size={18} /><span><strong>当前只是影响预览。</strong> 分析不会修改世界事实、人物认知、记忆或历史场景。</span></section><SectionCard title="历史改写请求"><div className="resource-list">{requests.data?.length ? requests.data.map(item => <article className="resource-row" key={item.id}><div><div className="resource-title">{item.latest_plan?.earliest_affected_sequence ? `从场景 ${item.latest_plan.earliest_affected_sequence} 起` : "待分析的世界修改"}</div><small>{item.reason}</small></div><span>计划 v{item.current_plan_version || 0}</span><StatusBadge value={displayStatus(item.status)} /><div className="actions">{item.latest_plan ? <Link className="button secondary" href={`/projects/${projectId}/retcon/plans/${item.latest_plan.id}`}>查看影响</Link> : item.available_actions?.includes("ANALYZE") ? <button disabled={analyze.isPending} onClick={() => analyze.mutate(item.id)}>开始分析</button> : <span className="muted">{item.available_actions?.map(term).join("、") || "-"}</span>}</div></article>) : <EmptyState title="还没有历史改写请求" description="从已完成预览的世界修订开始，生成一份可审计的因果影响计划。" />}</div></SectionCard>{open && <div className="dialog-backdrop"><form className="dialog" onSubmit={e => { e.preventDefault(); create.mutate(); }}><header><h2>新建历史改写</h2><button className="secondary" type="button" aria-label="关闭" onClick={() => setOpen(false)}>×</button></header><label className="field"><span>选择已预览的世界修订</span><select required value={revisionId} onChange={e => setRevisionId(e.target.value)}><option value="">请选择修订</option>{revisions.data?.filter(item => item.status === "PREVIEWED").map(item => <option value={item.id} key={item.id}>{item.title} · {item.id.slice(0,8)}</option>)}</select></label><label className="field"><span>修改原因</span><textarea required minLength={1} value={reason} onChange={e => setReason(e.target.value)} placeholder="说明为什么需要重新审视这段历史" /></label><footer><button className="secondary" type="button" onClick={() => setOpen(false)}>取消</button><button disabled={!revisionId || !reason || create.isPending}>创建请求</button></footer></form></div>}</main>;
}

export function RetconPlanView({ projectId, planId }: { projectId:string; planId:string }) {
  const query = useQuery({ queryKey:["retcon-plan", planId], queryFn:() => api(`/projects/${projectId}/retcon/plans/${planId}`) as Promise<any> });
  if (query.isLoading) return <LoadingState />;
  if (query.isError) return <ErrorState message="暂时无法读取影响计划。" retry={() => void query.refetch()} />;
  const plan = query.data.plan; const items = query.data.items || []; const grouped = (classification:string) => items.filter((item:any) => item.classification === classification);
  return <main className="stack"><PageHeader title="影响分析" description="这是一份历史依赖计划，不会自动修改或重演任何资源。" action={<StatusBadge value={plan.is_stale ? "计划已过期" : "已分析"} />} /><section className="preview-warning"><ShieldCheck size={18} /><span><strong>当前只是影响预览。</strong> 正式应用将在后续阶段提供。</span></section><section className="impact-summary"><div><small>最早受影响场景</small><strong>{plan.earliest_affected_sequence ? `场景 ${plan.earliest_affected_sequence}` : "暂无明确边界"}</strong></div><div><small>需要重新演出</small><strong>{plan.impact_summary.replay_scene_count || 0}</strong></div><div><small>需要重建认知人物</small><strong>{plan.impact_summary.affected_characters || 0}</strong></div><div><small>可以保留历史</small><strong>{plan.impact_summary.preserved_scene_count || 0}</strong></div></section>{[["REPLAY_REQUIRED","需要重新演出"],["REBUILD_COGNITION","需要重建认知"],["REVALIDATE","需要重新验证"],["UNCHANGED","可以保留"],["INVALIDATED","修改后将失效"]].map(([classification,title]) => <SectionCard title={title} key={classification}>{grouped(classification).length ? <div className="impact-list">{grouped(classification).map((item:any) => <article key={item.id}><strong>{item.resource_type} · {item.resource_id.slice(0,8)}</strong><p>{item.reason_summary}</p><small>{item.reason_code}</small>{item.dependency_path?.length > 1 && <div className="causal-path">{item.dependency_path.map((node:any, index:number) => <span key={`${node.id}-${index}`}>{node.type}{index < item.dependency_path.length - 1 ? " → " : ""}</span>)}</div>}</article>)}</div> : <p className="muted">没有该分类的影响对象。</p>}</SectionCard>)}<details className="developer-data"><summary>开发者数据</summary><pre>{JSON.stringify({ plan, items }, null, 2)}</pre></details></main>;
}
